/**
 * Unit tests for the two disable-inline-autogenerated-password settings:
 *
 *   1. disableInlineFillAutogeneratedPassword — unconditionally hides the inline
 *      autogenerated-password popup on every password field focus.
 *   2. disableInlineFillAutogeneratedPasswordWhenSiteExists — hides the popup only
 *      when a saved Login cipher already exists for the current site.
 *
 * The tests confirm:
 *   - Both settings default to `false` when no persisted value exists.
 *   - Each setter correctly persists the new value so it is reflected by the
 *     corresponding observable on the next emission.
 *   - Toggling one setting does not affect the other.
 */

import { mock } from "jest-mock-extended";
import { firstValueFrom } from "rxjs";

import { PolicyService } from "@bitwarden/common/admin-console/abstractions/policy/policy.service.abstraction";
import { AccountService } from "@bitwarden/common/auth/abstractions/account.service";
import { FakeAccountService, FakeStateProvider, mockAccountServiceWith } from "@bitwarden/common/spec";
import { UserId } from "@bitwarden/common/types/guid";
import { Utils } from "@bitwarden/common/platform/misc/utils";
import { RestrictedItemTypesService } from "@bitwarden/common/vault/services/restricted-item-types.service";

import { AutofillSettingsService } from "./autofill-settings.service";

describe("AutofillSettingsService — disable inline autogenerated password settings", () => {
  const mockUserId = Utils.newGuid() as UserId;
  let accountService: FakeAccountService;
  let stateProvider: FakeStateProvider;
  let policyService: ReturnType<typeof mock<PolicyService>>;
  let restrictedItemTypesService: ReturnType<typeof mock<RestrictedItemTypesService>>;
  let service: AutofillSettingsService;

  beforeEach(() => {
    accountService = mockAccountServiceWith(mockUserId);
    stateProvider = new FakeStateProvider(accountService);
    policyService = mock<PolicyService>();
    restrictedItemTypesService = mock<RestrictedItemTypesService>();

    service = new AutofillSettingsService(
      stateProvider,
      policyService,
      accountService as unknown as AccountService,
      restrictedItemTypesService,
    );
  });

  // ─── disableInlineFillAutogeneratedPassword ───────────────────────────────

  describe("disableInlineFillAutogeneratedPassword$", () => {
    it("defaults to false when no value has been persisted", async () => {
      const value = await firstValueFrom(service.disableInlineFillAutogeneratedPassword$);

      expect(value).toBe(false);
    });

    it("emits true after setDisableInlineFillAutogeneratedPassword(true) is called", async () => {
      await service.setDisableInlineFillAutogeneratedPassword(true);

      const value = await firstValueFrom(service.disableInlineFillAutogeneratedPassword$);

      expect(value).toBe(true);
    });

    it("emits false after being toggled back to false", async () => {
      await service.setDisableInlineFillAutogeneratedPassword(true);
      await service.setDisableInlineFillAutogeneratedPassword(false);

      const value = await firstValueFrom(service.disableInlineFillAutogeneratedPassword$);

      expect(value).toBe(false);
    });

    it("does not affect disableInlineFillAutogeneratedPasswordWhenSiteExists$", async () => {
      await service.setDisableInlineFillAutogeneratedPassword(true);

      const otherValue = await firstValueFrom(
        service.disableInlineFillAutogeneratedPasswordWhenSiteExists$,
      );

      expect(otherValue).toBe(false);
    });
  });

  // ─── disableInlineFillAutogeneratedPasswordWhenSiteExists ─────────────────

  describe("disableInlineFillAutogeneratedPasswordWhenSiteExists$", () => {
    it("defaults to false when no value has been persisted", async () => {
      const value = await firstValueFrom(
        service.disableInlineFillAutogeneratedPasswordWhenSiteExists$,
      );

      expect(value).toBe(false);
    });

    it("emits true after setDisableInlineFillAutogeneratedPasswordWhenSiteExists(true) is called", async () => {
      await service.setDisableInlineFillAutogeneratedPasswordWhenSiteExists(true);

      const value = await firstValueFrom(
        service.disableInlineFillAutogeneratedPasswordWhenSiteExists$,
      );

      expect(value).toBe(true);
    });

    it("emits false after being toggled back to false", async () => {
      await service.setDisableInlineFillAutogeneratedPasswordWhenSiteExists(true);
      await service.setDisableInlineFillAutogeneratedPasswordWhenSiteExists(false);

      const value = await firstValueFrom(
        service.disableInlineFillAutogeneratedPasswordWhenSiteExists$,
      );

      expect(value).toBe(false);
    });

    it("does not affect disableInlineFillAutogeneratedPassword$", async () => {
      await service.setDisableInlineFillAutogeneratedPasswordWhenSiteExists(true);

      const otherValue = await firstValueFrom(service.disableInlineFillAutogeneratedPassword$);

      expect(otherValue).toBe(false);
    });
  });
});
